### ISSUE TITLE
fix bug in getting the time series docstring to render

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/altairexpress#46]
The time series docstring will not render when running ```poetry run make html```
 in the `docs` directory. Therefore, the docstring can't be included in the ReadtheDocs website. 

This could be an issue with out the docstring is formatted potentially. Just in case, here is the link to the [numpy docstring guide](https://numpydoc.readthedocs.io/en/latest/format.html)

**Comment by zouwenjiao** [comment]
The bug has been fixed.
