### ISSUE TITLE
modify release.yml for continuous deployment 

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/altairexpress#51]
need to modify the release.yml so that we can still have branch protection AND continuous deployment 

- [instructions here](https://github.ubc.ca/MDS-2019-20/DSCI_524_collab-sw-dev_students/blob/master/lectures/06_lecture-cd-semver-and-docs.md#some-practical-notes-for-usage-in-your-packages-1)

**Comment by tejasph** [comment]
Has been implemented to master branch
